app:
  name: LawCrawlAgent
  version: 0.1.0
  mode: local

data:
  sources_path: "../data/sources.csv"
  storage_dir: "../data/docs"

database:
  primary: "sqlite"
  sqlite_path: "../data/law_demo.db"
  postgres_uri: "postgresql://user:password@localhost:5432/lawdb"

models:
  llm: "gemini-2.5-flash"
  embedding: "e5-large-v2"

graph:
  retry_limit: 2
  crawl_concurrency: 2
  crawl_delay_sec: 1.5
