# Cấu hình nguồn dữ liệu văn bản pháp luật

sources:
  # Nguồn chính thức - Cổng thông tin điện tử Chính phủ
  vanban_chinhphu:
    name: "Cổng Thông tin điện tử Chính phủ"
    base_url: "https://vanban.chinhphu.vn"
    search_url: "https://vanban.chinhphu.vn/portal/page/portal/chinhphu/NuocCHXHCNVietNam"
    priority: 1
    enabled: true
    crawl_delay: 3
    max_pages: 50
    selectors:
      list_item: "div.list-vb-item"
      title: "a.title-vanban"
      doc_number: "span.sohieu"
      doc_type: "span.loaivb"
      issuer: "span.coquanbanhanh"
      issue_date: "span.ngaybanhanh"
      pdf_link: "a.download-pdf"
    
  # Cơ sở dữ liệu văn bản pháp luật
  vbpl:
    name: "Cơ sở dữ liệu Văn bản Pháp luật"
    base_url: "https://vbpl.vn"
    search_url: "https://vbpl.vn/pages/portal.aspx"
    priority: 2
    enabled: false  # Sẽ bật ở bước sau
    crawl_delay: 3
    
  # Bộ Thông tin và Truyền thông
  mic:
    name: "Bộ Thông tin và Truyền thông"
    base_url: "https://mic.gov.vn"
    search_url: "https://mic.gov.vn/vbpq/Pages/Home.aspx"
    priority: 3
    enabled: false  # Sẽ bật ở bước sau
    crawl_delay: 3
    
  # Quốc hội
  quochoi:
    name: "Cổng thông tin điện tử Quốc hội"
    base_url: "https://quochoi.vn"
    search_url: "https://quochoi.vn/vanban"
    priority: 2
    enabled: false  # Sẽ bật ở bước sau
    crawl_delay: 3

  # Bộ Tư pháp
  moj:
    name: "Bộ Tư pháp"
    base_url: "https://moj.gov.vn"
    priority: 4
    enabled: false  # Sẽ bật ở bước sau
    crawl_delay: 3

# Cấu hình nguồn thảo luận (cho bước sau)
discussion_sources:
  vnexpress:
    name: "VnExpress"
    base_url: "https://vnexpress.net"
    enabled: false
    
  tuoitre:
    name: "Tuổi Trẻ Online"
    base_url: "https://tuoitre.vn"
    enabled: false
    
  thanhnien:
    name: "Thanh Niên"
    base_url: "https://thanhnien.vn"
    enabled: false
    
  duthaoonline:
    name: "Dự thảo Online - Quốc hội"
    base_url: "https://duthaoonline.quochoi.vn"
    enabled: false

# Cấu hình crawling chung
crawl_config:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  timeout: 30
  max_retries: 3
  retry_delay: 5
  respect_robots_txt: true
  concurrent_requests: 2
  download_delay: 2
